export function buildReadmeMarkdown(): string {
  return `# ChatGPT Context Export

This folder was generated by ChatGPT Context Bridge for Codex.

It contains the current ChatGPT conversation and related extracted artifacts.

## Files

- \`CODEX_TASK.md\`: Entry task file for Codex.
- \`full_conversation.md\`: Full chronological conversation.
- \`manifest.json\`: Metadata about this export.
- \`assets_manifest.json\`: List of detected assets and their save status.
- \`assets/\`: Extracted snippets, images, HTML, Markdown, and files when available.

## Recommended usage

Ask Codex to read \`CODEX_TASK.md\` first.
`;
}
